### ISSUE TITLE
improvement: add Dockers image

### ISSUE THREAD

**Issue by awb99** [zabirauf/icsharp#18] opened 2015-09-13 16:44 UTC
There are many dockers install scripts available for Jupyter, Jupyter R Kernel, etc.
This should also be done for the c# kernel.

Example:
https://github.com/cfljam/pyRat

**Comment by zabirauf** [comment] 2016-03-15 16:51
Duplicate of issue #23

**Closed by zabirauf** 2016-03-15 16:51 UTC
Labels: duplicate
